stages: [commit]
default_install_hook_types: [pre-commit, prepare-commit-msg]

repos:
  - repo: https://github.com/tcort/markdown-link-check
    # Stick to 3.11.2 until https://github.com/tcort/markdown-link-check/issues/325 is fixed
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
        args: ["--quiet", "--config", ".md-link-config.json"]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: ["--dot", "--fix"]
        exclude: |
          (?x)^(
            .github/pull_request_template.md
          )
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - linkify-it-py==1.0.3
          - mdformat-gfm==0.3.5
          - mdformat-myst==0.1.5
          - mdformat-shfmt==0.1.0
          - mdformat-config==0.1.3
          - mdformat-toc==0.3.0    